#!/usr/bin/env node
/**
 * Minimal static file server for the end-to-end tests. It serves the `out/` export the way a real
 * static host does, so the tests exercise what ships:
 *
 *   - `/about/` resolves to `about/index.html`; `/about` redirects to `/about/` (trailingSlash)
 *   - an unknown path returns `404.html` with status 404
 *   - response headers come from `out/_headers` (generated by scripts/postbuild.mjs), including the
 *     Content-Security-Policy, so a CSP violation shows up as a console error in the browser
 *
 *   - the policy in each page's <meta http-equiv="Content-Security-Policy"> tag (written into every
 *     html file by postbuild) is served as built, so a host without header support is covered too
 *
 * One deliberate difference: `upgrade-insecure-requests` is removed from the CSP, in the header and
 * in the <meta> tag. The tests run over plain http://127.0.0.1, where the directive would rewrite
 * same-origin requests to https. Everything else in the policy is served exactly as built.
 *
 * `serve` is not a dependency and the project adds none, hence this file.
 *
 * Usage: node tests/e2e/static-server.mjs [--dir out] [--port 4173] [--host 127.0.0.1] [--csp-header on|off]
 * `--csp-header off` drops the Content-Security-Policy header, which is what Vercel and a plain file
 * server send, so a test can prove the <meta> policy in the HTML holds on its own.
 * Use --port 0 to pick a free port; the chosen address is printed as "listening http://host:port".
 */

import { createServer } from "node:http";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { headersForPath, parseHeadersFile } from "../../scripts/lib/csp.mjs";

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".map": "application/json; charset=utf-8",
  ".pdf": "application/pdf",
};

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

function parseArgs(argv) {
  const options = { dir: "out", port: 4173, host: "127.0.0.1", cspHeader: true };
  for (let i = 0; i < argv.length; i += 2) {
    const flag = argv[i];
    const value = argv[i + 1];
    if (value === undefined) throw new Error(`${flag} needs a value`);
    if (flag === "--dir") options.dir = value;
    else if (flag === "--port") options.port = Number(value);
    else if (flag === "--host") options.host = value;
    else if (flag === "--csp-header") options.cspHeader = value !== "off";
    else throw new Error(`Unknown argument: ${flag}`);
  }
  if (!Number.isInteger(options.port) || options.port < 0 || options.port > 65535) {
    throw new Error(`Invalid port: ${options.port}`);
  }
  return options;
}

async function fileInfo(file) {
  try {
    const info = await stat(file);
    return info.isDirectory() ? "dir" : info.isFile() ? "file" : null;
  } catch {
    return null;
  }
}

function contentTypeFor(file, body) {
  const known = TYPES[path.extname(file).toLowerCase()];
  if (known) return known;
  // Metadata image routes are exported without an extension.
  if (body.subarray(0, 4).equals(PNG_MAGIC)) return "image/png";
  return "application/octet-stream";
}

/** The CSP as built, minus the directive that only makes sense over https. */
function adaptHeader(name, value) {
  if (name.toLowerCase() !== "content-security-policy") return value;
  return value
    .split(";")
    .map((directive) => directive.trim())
    .filter((directive) => directive !== "" && directive !== "upgrade-insecure-requests")
    .join("; ");
}

/** Same adaptation for the policy inside the HTML's <meta> tag. */
function adaptHtml(body) {
  const text = body.toString("utf8");
  const adapted = text.replace(
    /(<meta\s+http-equiv="Content-Security-Policy"\s+content=")([^"]*)(")/i,
    (_all, open, policy, close) =>
      `${open}${adaptHeader("Content-Security-Policy", policy)}${close}`,
  );
  return adapted === text ? body : Buffer.from(adapted, "utf8");
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const root = path.resolve(options.dir);

  if ((await fileInfo(root)) !== "dir") {
    console.error(`static-server: ${root} does not exist. Run "pnpm build" first.`);
    process.exit(1);
  }

  const headersText = await readFile(path.join(root, "_headers"), "utf8").catch(() => "");
  if (headersText === "") {
    console.warn("static-server: out/_headers is missing, serving without security headers.");
  }
  const rules = parseHeadersFile(headersText);

  /** Absolute file under root for a URL pathname, or null when it would escape root. */
  const locate = (pathname) => {
    const target = path.resolve(root, `.${path.posix.normalize(`/${pathname}`)}`);
    return target === root || target.startsWith(root + path.sep) ? target : null;
  };

  const server = createServer(async (request, response) => {
    const send = (status, rawBody, type, extra = []) => {
      const body = type.startsWith("text/html") ? adaptHtml(rawBody) : rawBody;
      const headers = new Map();
      for (const [name, value] of headersForPath(rules, pathname ?? "/")) {
        if (!options.cspHeader && name.toLowerCase() === "content-security-policy") continue;
        headers.set(name.toLowerCase(), [name, adaptHeader(name, value)]);
      }
      // Tests must see the file on disk, not a cached copy of an earlier build.
      if (!headers.has("cache-control"))
        headers.set("cache-control", ["Cache-Control", "no-store"]);
      headers.set("content-type", ["Content-Type", type]);
      headers.set("content-length", ["Content-Length", String(body.length)]);
      for (const [name, value] of extra) headers.set(name.toLowerCase(), [name, value]);
      response.writeHead(status, Object.fromEntries(headers.values()));
      response.end(request.method === "HEAD" ? undefined : body);
    };

    let pathname;
    try {
      if (request.method !== "GET" && request.method !== "HEAD") {
        pathname = "/";
        return send(405, Buffer.from("Method not allowed"), "text/plain; charset=utf-8", [
          ["Allow", "GET, HEAD"],
        ]);
      }
      const url = new URL(request.url ?? "/", "http://localhost");
      if (url.pathname.includes("\0") || /%00/.test(url.pathname)) {
        pathname = "/";
        return send(400, Buffer.from("Bad request"), "text/plain; charset=utf-8");
      }
      pathname = decodeURIComponent(url.pathname);

      const target = locate(pathname);
      if (target === null) {
        return send(404, Buffer.from("Not found"), "text/plain; charset=utf-8");
      }

      let file = target;
      const kind = await fileInfo(target);
      if (kind === "dir") {
        if (!pathname.endsWith("/")) {
          return send(301, Buffer.alloc(0), "text/plain; charset=utf-8", [
            ["Location", `${url.pathname}/${url.search}`],
          ]);
        }
        file = path.join(target, "index.html");
      }

      if ((await fileInfo(file)) === "file") {
        const body = await readFile(file);
        return send(200, body, contentTypeFor(file, body));
      }

      const notFound = await readFile(path.join(root, "404.html")).catch(() => null);
      return notFound
        ? send(404, notFound, TYPES[".html"])
        : send(404, Buffer.from("Not found"), "text/plain; charset=utf-8");
    } catch (error) {
      if (error instanceof URIError) {
        pathname = "/";
        return send(400, Buffer.from("Bad request"), "text/plain; charset=utf-8");
      }
      console.error("static-server:", error);
      return send(500, Buffer.from("Server error"), "text/plain; charset=utf-8");
    }
  });

  server.listen(options.port, options.host, () => {
    const address = server.address();
    const port = typeof address === "object" && address ? address.port : options.port;
    console.log(`listening http://${options.host}:${port} (${root})`);
  });

  const stop = () => server.close(() => process.exit(0));
  process.on("SIGINT", stop);
  process.on("SIGTERM", stop);
}

main().catch((error) => {
  console.error(`static-server: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
